name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get install -y clang-10 libelf-dev
    - name: Symlink clang
      run: sudo rm -f /bin/clang && sudo ln -s /usr/bin/clang-10 /bin/clang
    - name: Build
      run: cargo build --verbose --workspace --exclude runqslower
    - name: Run tests
      # Skip tests that require BTF built into kernel
      run: cargo test --verbose --workspace --exclude runqslower -- --skip test_object
    - name: Run rustfmt
      run: cargo fmt --package libbpf-cargo libbpf-rs -- --check
    - name: Run clippy
      run: cargo clippy -- -D warnings
